version: 2.1
executors:
  docker-executor:
    docker:
      - image: krztybkrr/animboom:linux

jobs:
  files-format:
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run clang-format
          command: |
            python3 .ci/run-clang-format.py -r src
      - run:
          name: Run qmlformat
          command: |
            python3 .ci/run-qmlformat.py -r main.qml ui

  build-tests:
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Create build directories
          command: |
            mkdir -p build
      - run:
          name: Setup cmake and build artifacts
          command: |
            cd build
            cmake .. -DENABLE_TESTS=ON
            cmake --build . --config Release
      - run:
          name: Run ctest
          command: |
            cd build
            ctest

workflows:
  version: 2
  build-with-tests:
    jobs:
      - files-format
      - build-tests
