name: file-format

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container:
        image: krztybkrr/animboom:linux
    steps:
      - uses: actions/checkout@v3
      - run: |
            python3 scripts/run-clang-format.py -r src QmlImports
