name: file-format

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  file-format:
    runs-on: ubuntu-latest
    container:
        image: krztybkrr/animboom:linux
    steps:
      - uses: actions/checkout@v3

      - name: clang-format
        if: always()
        run: |
          python3 scripts/run-clang-format.py -r src QmlImports

      - name: qmlformat
        if: always()
        run: |
          python3 scripts/run-qmlformat.py -r QmlImports QmlContent
